PINECONE_API_KEY = "610b639f-dad6-48f9-a78a-7a55ca351a4c"
PINECONE_ENVIRONMENT = "gcp-starter"
PINECONE_INDEX = "geminiindex"
PINECONE_SEO_INDEX = "geminiindex"
GEMINI_API_KEY = "AIzaSyDcF1LrSLzb9l3B7NfS_5LFNyoGnMv6K_g"
DOC_DIR_PATH = "./documents/"
